### ISSUE TITLE
Privilegis escriptura

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/GitTest#1]
I don't know if I've given you Privilegis escriptura

**Comment by davidromani** [comment]
Yes, now I have "write permission" to push my code directly.

**Comment by davidromani** [comment]
I don't have write permissions yet. When I try to push something I've got this error:

```
$ git push
ERROR: Permission to aserratorta/GitTest.git denied to davidromani.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

Check this example in your main repository page:
![captura de pantalla 2015-06-22 a les 8 50 38](https://cloud.githubusercontent.com/assets/698779/8276877/0c31296a-18bc-11e5-9738-53b27d5bebdf.png)

**Comment by aserratorta** [comment]
I think I've done it!

**Comment by davidromani** [comment]
Yes, well done! Pull my new commit https://github.com/aserratorta/GitTest/commit/80fba37533d42a55a79cf1d02a0e76afbf68926c to your repo and tell me something
