### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by davidromani** [aserratorta/GitTest#3]
Create a README (txt) file on root dir with a little documentation about this repository. Keep in mind that a lot of people can show or clone it.

**Comment by aserratorta** [comment]
Like this?#3

**Comment by davidromani** [comment]
No. I'm talking about the comment (text) inside the "git commit -m" command. It's only a warning for next issues.

**Comment by davidromani** [comment]
No. I'm talking about the comment (text) inside the "git commit -m" command. It's only a warning for next issues.
