### ISSUE TITLE
Merge practice

### ISSUE THREAD

**Issue by davidromani** [aserratorta/GitTest#4]
Try to merge devel into master branch. Apply this steps to do it well:
- jump to devel branch
- pull devel remote changes into your computer
- jump to master branch
- merge devel branch (a new commit will be set)
- push local changes to remote

Good luck!
bonus: use "--no-ff" option during merge action if you can ;-)

![captura de pantalla 2015-07-02 a les 18 35 21](https://cloud.githubusercontent.com/assets/698779/8482542/9d144f8a-20ea-11e5-9161-7f4f75dd6f41.png)

**Comment by aserratorta** [comment]
My steps to do it:

Anton@SERRAMESTRE ~/ProvaGid (master)
$ git checkout devel
Switched to branch 'devel'
Your branch is up-to-date with 'origin/devel'.

Anton@SERRAMESTRE ~/ProvaGid (devel)
$ git status
On branch devel
Your branch is up-to-date with 'origin/devel'.

nothing to commit, working directory clean

Anton@SERRAMESTRE ~/ProvaGid (devel)
$ git pull origin devel
From https://github.com/aserratorta/GitTest
- branch            devel      -> FETCH_HEAD
  Already up-to-date.

Anton@SERRAMESTRE ~/ProvaGid (devel)
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

Anton@SERRAMESTRE ~/ProvaGid (master)
$

Anton@SERRAMESTRE ~/ProvaGid (master)
$

Anton@SERRAMESTRE ~/ProvaGid (master)
$ git merge --no-ff devel
Auto-merging Doctexto.txt
CONFLICT (content): Merge conflict in Doctexto.txt
Automatic merge failed; fix conflicts and then commit the result.

Anton@SERRAMESTRE ~/ProvaGid (master|MERGING)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

```
    modified:   Doctexto.txt
```

Anton@SERRAMESTRE ~/ProvaGid (master|MERGING)
$ git commit -am "Doctexto.txt fixed"
[master a1deb4e] Doctexto.txt fixed

**Comment by davidromani** [comment]
Very good.

Put your attention on merge conflicts, when this happends **first** you must resolve it (edit file) and **second** make a commit. Finally, remember to push changes like always.

```
CONFLICT (content): Merge conflict in Doctexto.txt
Automatic merge failed; fix conflicts and then commit the result.
```
