### ISSUE TITLE
ssh keygen

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/GitTest#5]
![imagen1](https://cloud.githubusercontent.com/assets/12971681/8509739/26dc72ca-22b6-11e5-843b-c317381cbd46.png)

I'm trying to solve the problem with my keys. I'm trying to do it through this picture I show you.
I'm not sure about my host. Can you give me some clue, please? I thought it was my IP or https://github.com/aserratorta/GitTest.git, but it dosesn't work.

Thanks

**Comment by davidromani** [comment]
you need to launch ssh agent before
